apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkmk-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  mountOptions:
    - hard
    - nfsvers=4.1
  claimRef:
    namespace: checkmk
    name: checkmk-pvc
  nfs:
    server: __NAS-HOST__
    path: /volume1/kub/homelab/checkmk
    readOnly: false
