apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-pvc
  namespace: checkmk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: storage
  volumeName: checkmk-pv
