apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-db
  claimRef:
    namespace: paperless
    name: pgsql-pvc
  nfs:
    server: ${NAS_HOST}
    path: /volume1/kubdbs/homelab/paperless
    readOnly: false
