apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-apps
  namespace: velero
  labels:
    tier: daily
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
      - fing
      - hoarder
      - homarr
      - homelab
      - jellyfin
      - libre
      - monitoring
      - n8n
      - paperless
      - rss
      - vscode
    excludedResources:
      - events.events.k8s.io
      - events
    snapshotVolumes: false
    defaultVolumesToFsBackup: true
    ttl: 168h
    storageLocation: wasabi
