apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monthly-apps
  namespace: velero
  labels:
    tier: monthly
spec:
  schedule: "0 5 1 * *"
  template:
    includedNamespaces:
      - fing
      - hoarder
      - homarr
      - homelab
      - jellyfin
      - libre
      - monitoring
      - n8n
      - paperless
      - rss
      - vscode
    excludedResources:
      - events.events.k8s.io
      - events
    snapshotVolumes: false
    defaultVolumesToFsBackup: true
    ttl: 8760h
    storageLocation: wasabi
