apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - nodiratime
    - rw
  claimRef:
    namespace: vscode
    name: code-server-pvc
  nfs:
    server: ${NAS_HOST}
    path: /volume1/kub/homelab/vscode
    readOnly: false
