apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: vscode
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage
  volumeName: vscode-pv
