apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vscode-secret
    namespace: vscode
data:
    password: ENC[AES256_GCM,data:1xwvUHuGmUMm+0Bu,iv:bTc75Zb6MSnCEZBvaAbMSi9jdCqFBGlSe6bZNavaPQQ=,tag:KTI8NHDqva3hpmvo+g9hTw==,type:str]
    sudo-password: ENC[AES256_GCM,data:N2CRPHVHbJyCVFJI,iv:oKZzV6rMChi/WYLdH5WsXpfoljx5nDBnU/Vhgf20QiU=,tag:lcPAQMrl6rBdOHzUV+IPXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4azE3bG9PSDZzSW5YNnA4
            a2REZDdGZnQ4NnI0RklXWU5McHppSngrZzBBCll4MFJWSEc4WTNlSFZYL2hESkJH
            WHkza3kwTTBHeG5QWE1LZ2o4Sjl5aVUKLS0tIEVPREpiZDlVWEJsWk4yb2txcDZo
            MnlBcjhzVDJEeEh4ZHBRWVQrY2syNkUKouUZTJWLYSRAOhZ0//TI3AzamvG9r09O
            0qG19O3gf/4DlePTr5HeKED9CKgCH86ZFJa8EZMylhPsYPvRB2/Oig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:07Z"
    mac: ENC[AES256_GCM,data:LtqtgLmFiEEW2oq8fjslTcf8d1xMiERN9KYZcm1xtsZazrLUkwd3zsYlSHF/twXCpEGchWSINlCj2BPwGq6suaPkQHKiCYQsfhPNQKzXSBbW30dwAAb1cgmRXltyvgFMQ6eDyOoU5b3p90XRARAW4WqiktpVoF8ZPZblx6yq88w=,iv:xTWN9Ml2gkVJ+pUIlmhnrn7JjlHfTJpUZYnSmdoCSgk=,tag:elV8g/JgpcdbIdMNX8+OMg==,type:str]
    version: 3.13.0
