apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-database
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-db
  volumeName: homarr-database
