apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: db-secret
    namespace: homarr
data:
    db-encryption-key: ENC[AES256_GCM,data:AplkBl9wL+v1JdkLO/zeWOdlOq0/UmWoT3QROT4quH2urR/7xsIKByTKjOIhQ2jCVTa/0mg3Eph3Dd9DlwbDOQckKYLXNSUdfmQz+SQnRDzuO/HtK0IBtw==,iv:cggeSRO0MkOdSJxvUbhpLwCufUVuUaWx57hfLMbXa+U=,tag:ZKgRM9wJXW0BYkav7O5RlQ==,type:str]
    db-url: ENC[AES256_GCM,data:LE+NZK7M1Tfoo4WB+vD7DU0AEPUFxZl2qXj955w1Afn1Rm87KxyyMu+s6C8GKqcetwL25W9+ovX1P27YCTLfCAev9PkLZ9Pdj6/7HEzj4ug=,iv:w22RubdQZQX+QsLWjm0cjqCxtovy2Kgy/y7M0D+MxDY=,tag:O9qJKzqN1nAlfK4unTagIA==,type:str]
    mysql-password: ENC[AES256_GCM,data:WYw9lk8muNIiBkRs,iv:gz5uVn6c5QESce9dreEi0HMlN/keDH1Zv87TgEwVmus=,tag:WvO68apuHcMR9dKQwvScgA==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:58zqg7rsw0mlAHFI,iv:A5AVx8ETWzl8h6y4Zfs0EjIouOzzlOEylOLwsV/De2A=,tag:13jbitQejNoJvhhQv6TL6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSUdTOW5XUGFwcStzQzRu
            dWVia2cvZE5UeVNqM080ZVJNdzBqczR4SGdjCm9uRmV2T3pYWnhEWk1ITndoTmZq
            MFBYUzlxNkNNV1pwU3FoVE1zY1N6UlkKLS0tIGZtM29uNFNMZy9sRjc1aXc5UmZu
            V1hxbWFyd2RQYzNGVi8yd1dURjR1dlEKBZauHbZO+7TRfNU6xK2yp5A8S7JEhW2E
            bJM14KR2cWhMFNe+6XserUxxYf7WGiGS/d4cNv3nJ5sfaaJ72kKT9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:06Z"
    mac: ENC[AES256_GCM,data:OtG5CddbO+wDouahxKxu+Pu5pok4meO6DcCca+65qDB7+aecgs/sNCadu2r355xIWrU+oLQrkC925dm8D0UNTG14ZEf5rJQrW7OY53TP3SGc8l5va4LpLFVJHVNoKqeCTwgx1AupJlgEAEyhimrh/9FC9XtllZiAyrh+fZJIjO8=,iv:xT8eKoY6DWIaFqqUMzuNCDH5sYXwJawInp/YPKcvmrA=,tag:Luvb5es0toQxgdwF/MvuMA==,type:str]
    version: 3.13.0
