apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  mountOptions:
    - hard
    - nfsvers=4.1
  claimRef:
    namespace: firefly
    name: firefly-pvc
  nfs:
    server: ${NAS_HOST}
    path: /volume1/kub/homelab/firefly
    readOnly: false
