apiVersion: v1
kind: Secret
metadata:
    name: firefly-secrets
    namespace: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:o1BYxRxPjWHT3AgZScDjNmM4Y+FyDFXUvP20a2BnsVXhLeM3pRHR3La2o3MsN5A4wfsK,iv:4WShjajMqOnSIjl9KeATqM3H6IEd2f8ukPunrB+Cf1g=,tag:NrmzJ6JPgUbCWeA1xYmVIQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Iw8bqMrEzKjBOOKdlEYAMrfAJfHxcT3gurq9,iv:v2VRlQ/pWy9W6ANSXbstGyZJy/vpnspiNcFbhuem5kg=,tag:u3+isWsAY4JxRQu8+7y9cg==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:0Rqxm1zG/Mf/GFmSFzMkJNRyPoAfVMsG4Yrc7evM9uE=,iv:nWOWGw5OQPOm0yibpFcZ1Bl1IPixXMXPQAnXWkAZk8U=,tag:NhQh6v/7zjpGNY6JewaitA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVldaSWxpM3FaODdrWC9V
            cTJSQ0pQYU5DSWZnQkw2OGdrR2lEeExFQkNZCjUzZi9CVSszV1pwWE40UDZMNkx2
            S21iblIwMzc4L3l6cGZLMVhNZlVidk0KLS0tIHlvL3ZkOXR6UVhuTlBYRUhZdzN6
            QzRMT1U5ZEJudzlpYkJmUUxjOTZSS3MKoaEnLikcFLW51E7m3xdyYwXdGMgiv1uj
            X5/5vrUlqSJDy0UCAqZnNwAK7/Er0XfWybNYC04t+wvesjvM3FoDAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:44:57Z"
    mac: ENC[AES256_GCM,data:OkvIr2kq6DseOOTcMWz5MukbbgGiEZQtQcYpHCFofKJ+3d5Oh9W1TIfJ2XktRsAztW/hdo+UrXJYi79ZnVBBt21fyq1m8bsnny3Si8ep8yTKqdnMWJKqeh52UUqtmcvtwVbZdTNLmWUKXOhxGQWjAdodMCgiLOZ9Uoa13gT+oT4=,iv:oDZ1aeWjOeijV2sST9bMEgkBU3nr+2H0QJTQ700527c=,tag:Aq/ck0q21rAshsKX/9v2GQ==,type:str]
    version: 3.13.0
