apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: hoarder
  labels:
    app: meilisearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.42.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7700
              protocol: TCP
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: meilisearch-pvc
