apiVersion: v1
kind: PersistentVolume
metadata:
  name: hoarder-meilisearch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  claimRef:
    namespace: hoarder
    name: meilisearch-pvc
  nfs:
    server: ${NAS_HOST}
    path: /volume1/kub/homelab/hoarder/meilisearch
    readOnly: false
