# Dynamic PVC against storage-apps SC (Wave 1, 260511-utf).
# Path: __NAS-IP__:/volume1/kub/homelab/hoarder/meilisearch-pvc/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-ssd
