apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hoarder
  namespace: hoarder
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hoarder.${BASE_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: crowdsec-bouncer
          namespace: kube-system
      services:
        - name: web
          port: 80
