apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secrets
    namespace: hoarder
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:P8VonIcrfxYi8Efnf+0+gGDmRBMGkh6uBudLw9lv9Wa8jPhtg4sppD2kP8Tz0UzD,iv:KpDdCiWGMyq/A9dOQ8ayKTAAvZ7ZtIac0t3cRX4nhog=,tag:kFEJPUliA/4BV1MvpNqEZA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:ZmqYSXuIs52aLi2zFdg6vMm6Hj527SWoCVO1xt3XGW3vXdaI+YTpInKhsmRapgKH,iv:YcZVfsR1S2Ynkt97ulUX/TXLsDqYA7UwfSeRZ64ujAg=,tag:xOoces5Fcs99SyT4Nf4+6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdzF1dEZhUWg5dit6SXFh
            UUNsTExhZ3plWTVLQmRlaThwMmZTbmxadGowCmcvcjBSbzA0VE0vejJyMUtheXFw
            c2tpNldrRGhZT3VkTVl2VXpuSnlVNXcKLS0tIHFMZXZITXdNME9maEM3Ulp1K2Fx
            c1hySUhTY2NVZVViVy9JZGMwdEdyZGMK2f9ktBtJEIL2Ss4AgoBAN+NsFZHJFsoj
            bgZ/tcm8q2Gu1yvOweMlbYq5SY+cF1LuRCp0NUgqXFBwAkSxUvGB3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:50:40Z"
    mac: ENC[AES256_GCM,data:9pENl6y+C6CyOcJyv8hgDK0NwdxIX7Xywj66FiWq8CoC6z5ICLtlFnP5vx7oSFEjVjaWjmShBL1usfkGPVdWB5/0ci051wBr14MisM9yJkC4ecqd+rVsBLPDGvk5kff6uiw6j9i8yuIxedChfeEcnrc8NcRYsT6XxegPqGO1p9k=,iv:Lcmi4/Qx3vzoXYuyEDvu4wJyiXe2Kg82FdGMUaw34dw=,tag:0e2vPbPyz9cvAMqLTHxTJQ==,type:str]
    version: 3.13.0
