apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitjat-mirror-pvc
  namespace: fitjat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage
  volumeName: fitjat-mirror-pv
