# Dynamic PVC against storage-apps SC (Wave 2, 260511-utf).
# Path: __NAS-IP__:/volume1/kub/homelab/dashy/dashy-pvc/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-pvc
  namespace: dashy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-apps
