apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libreoffice-pvc
  namespace: libre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage
  volumeName: libreoffice-pv
