apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vaultwarden-admin
    namespace: vaultwarden
stringData:
    admin-token: ENC[AES256_GCM,data:GmpA78IhcwcL28e2yYN0AJ/5mIt4FM2XblxtPT+CJIP98W+0V4OCb6FYBcgxzAvd,iv:I9TAty3kI0YVUOrUNOBfQBNnMw0XqSetrC5kQOqJ2EQ=,tag:nFEVL3SgFaENMXXx9a6YpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SExnZkFVMy9vRXNBbkxu
            K0JzUWc4bkxzZjdtSld0d0hJT2RvRjN1YUJ3CkdWdi9taXJQQ1V5SFJIN0ZaS1V1
            NUV6UDB0djFnQVRPVkRReWNkRGNuTGcKLS0tIEpObkovRGhCaHZlVi82bUxNb3FR
            eG1QemNCQmxJamFtVzVEWUM4cXhjbUEK8S+/mhj6vIuwiHEEFQr7flTein8YVA+B
            qJMQJmflxlNThqOC1a6APKdAgHdk5ll12RXog1EMMZu65WHi0CrK4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T01:13:45Z"
    mac: ENC[AES256_GCM,data:ily51TTEnK4RfWplIJEIjDOroFLaEKQzur/X2uTp8ldksAtqcPQDDrf0zYQaLMbVkMRRROap1+kWTOzl99LYx6jxFHCZab12MiAgFEh97m8QrWEuQ+CFwQ1oUq2HTyLDgT3sJheNCIoqvoauS0diXNnHTpbrQfkan5hRhiTkfXM=,iv:SnfFogjUJW7B78vXD42Y3O/xOciHPdQ04uZ1uLSU71A=,tag:A1cFDI2dronpQzXVogK/hg==,type:str]
    version: 3.13.0
