apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-secret
    namespace: paperless
data:
    admin-password: ENC[AES256_GCM,data:WqutR1sSeVqhktpEBVI9s9Nh84NgQTrIiXr4Atx8nHs=,iv:Kx57yT/5R7yj/ZrtRYJddG85tkGnJbT3/sW3yctyGNc=,tag:hHSUFqliLl1AXmSCJgiP0A==,type:str]
    admin-user: ENC[AES256_GCM,data:udz/tkH4fS8=,iv:bU9aC5TO05LMlNFLBifOvrD2IwTu3XIB8tYrjX578TM=,tag:emzkIxugQGlbKietvTF4gg==,type:str]
    db-password: ENC[AES256_GCM,data:iNXzVNuB6LJpTEeL+uGBJPMEocCpGejt,iv:JayjpaaacJPlxvj/yQrstlHjR7lPha7d9xoJWruI+L4=,tag:qbxiMCkH6GHnYVLMkqjkfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVGV1MWY4blN3eDAvdDNT
            Rk5zemVsNDBCWGxCZWN4bE1xcmQ4VjZJWFdzCit3MzBROWk0QXoyRFNPcVlVb1Nk
            Rnp4VzNmS3hkbC81T1lLeVlNZFdibk0KLS0tIHpBRlJpTGh6Yng0S3FMckgxazV2
            cWxjdTZ6Vi9NMjVVWXI0TE5lS0dzZ1UK3B4IHBMNCYRvHl5VqofBF8o4+O+jQAjQ
            YJnErB5osRldTvFNBHHQKRWuDf7mC+5jmukS5WmuJaS7ZTw4aK+Fxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:07Z"
    mac: ENC[AES256_GCM,data:UNhUUm3v7yT59GCHFtbNNfEjB/y61VP2OhHUhDpCgwvRqgWU88Lyckq7Wkheak4iG0WEQZ28h/DXJACs/NAZq1W2eFVwgcUKY4TehW9mhMYv/fN2+7R5u8ShGIOIv+qnMwoib3ngfQnAXKeSWefGJHL0clGw5rSKPgXOOZQyAPk=,iv:tvtgxcylE8+I+RGTUlY7/LGuEhTky3OMjayuJowmdso=,tag:n1cDRlDNbieIGGKesVY8oA==,type:str]
    version: 3.13.0
