apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-secret
    namespace: paperless
data:
    admin-password: ENC[AES256_GCM,data:WqutR1sSeVqhktpEBVI9s9Nh84NgQTrIiXr4Atx8nHs=,iv:Kx57yT/5R7yj/ZrtRYJddG85tkGnJbT3/sW3yctyGNc=,tag:hHSUFqliLl1AXmSCJgiP0A==,type:str]
    admin-user: ENC[AES256_GCM,data:udz/tkH4fS8=,iv:bU9aC5TO05LMlNFLBifOvrD2IwTu3XIB8tYrjX578TM=,tag:emzkIxugQGlbKietvTF4gg==,type:str]
    db-password: ENC[AES256_GCM,data:iNXzVNuB6LJpTEeL+uGBJPMEocCpGejt,iv:JayjpaaacJPlxvj/yQrstlHjR7lPha7d9xoJWruI+L4=,tag:qbxiMCkH6GHnYVLMkqjkfw==,type:str]
    secret-key: ENC[AES256_GCM,data:dEe0be5w+E00MB88i0liX3LCga+FWpetbplPD9SxzUG8/3XXgxNRSgD2yuzZEqJhgCcG3uub9+kbtDusL9E2mdOHV4/2xbisUpTSax5vGV3kkW66GXYE0hoFOqTYu+WTAKD5cPZ8wR6NyZc5v/kMQ1CJWU0=,iv:hR9I158OuaCCCmhWy5V4yqZLYePxYs+cYSpNb6Qws4Y=,tag:0qL6d/F0mXvm3Ce23hMAiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVGV1MWY4blN3eDAvdDNT
            Rk5zemVsNDBCWGxCZWN4bE1xcmQ4VjZJWFdzCit3MzBROWk0QXoyRFNPcVlVb1Nk
            Rnp4VzNmS3hkbC81T1lLeVlNZFdibk0KLS0tIHpBRlJpTGh6Yng0S3FMckgxazV2
            cWxjdTZ6Vi9NMjVVWXI0TE5lS0dzZ1UK3B4IHBMNCYRvHl5VqofBF8o4+O+jQAjQ
            YJnErB5osRldTvFNBHHQKRWuDf7mC+5jmukS5WmuJaS7ZTw4aK+Fxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T15:19:20Z"
    mac: ENC[AES256_GCM,data:VIzq+gHZFIAAHLIM3IXfFU62Qb+pthzmS4yXG3muKXyCHm60fjmH7JCs9cTDeX7kIIVa/OXJd5Y01Qn9p7tJSl07Zpimh80cyx5UDwyjtv2waZ8YnH+RyBRcjpi/hmN1fi8trJRjxwhIsXLsHZhWqew1Z8F7C0XSwaTeghzq+DQ=,iv:zyH8koXxYTX3QvIjA03svfjYQ5/BXAVw2AUMPsDP9PM=,tag:6HVfZrvgZLGndZ9gq8UjIQ==,type:str]
    version: 3.13.0
