apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ciso-assistant-secret
    namespace: ciso-assistant
stringData:
    password: ENC[AES256_GCM,data:T0ZZZJEVwekL2VCpARukDQf1P/DV+la3H8snfg==,iv:KqeS73BssOK3VA9tQ6lAKKVB1u16AqgvO5kvXXeXsTg=,tag:0Iy8wd/JBFiypz2sCklBtw==,type:str]
    django-secret-key: ENC[AES256_GCM,data:g+4x+YMPAbw6BzTwi3pP0VqYab5SjWeV5PgmW3zkeNa+W0ge/+WcJvnn4oVrWX9HhP0=,iv:J5KKyq+hr7zUkaUDtsHBaz9TdAYOCHn3oSNF24+hR2Q=,tag:6NhlMq5+xubewwIMj29zZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTczl6OUdQTTROL0NMblpT
            ZGx1YXpNbWc2RHNaaHlmRmhIYmc1ZWNTWEJjCjZyeEVlN1FrVUx0MEpoV1RzazJT
            SWdSZjJKWlNRenpSRUx3ZzZvWnlQUmMKLS0tIGVKNG1Ubkh0b2QrcHMxV2gzM2JZ
            alIya3FYL09nTCtvYXRCd2lxdVl6eU0Kpo1QE4QCGpzOxj6dXY/ehu7yz5y8CfRy
            vqFv+5iK5BYH7UMbZ7Te7wIsA5UsS8jSmMP4OdQrGyHmvYd/tftwzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:30:30Z"
    mac: ENC[AES256_GCM,data:2Ue1XxDO4pwM0CFubEwpTbGlBpsXErxHneUZCZ+wTAEcpx2Hv+s+t5eiMY7OoR8Rw8qdLkqvKGW+TRbZ0dNJLRndxeysoPKRSHDpfuebKMxTfYaGRzkDm326k3nQdT1MI53CKBh+mlwacTY4j8rFqlVEapkFzopuhJbCH5fxLgg=,iv:xL4xd28DyXvIW1mKVtaREY47gEAKc3hR6ZA+JcmyNzk=,tag:Nh5USiYLCTXjO45Vno20PQ==,type:str]
    version: 3.13.0
