apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless
  labels:
    app: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ngx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes-excludes: data-volume,media-volume
      labels:
        app: paperless-ngx
    spec:
      containers:
      - env:
        - name: PAPERLESS_URL
          value: https://paperless.__BASE-DOMAIN__
        - name: PAPERLESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: paperless-secret
        - name: PAPERLESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: paperless-secret
        - name: PAPERLESS_REDIS
          value: redis://redis:6379
        - name: PAPERLESS_DBHOST
          value: postgres
        - name: PAPERLESS_DBNAME
          value: paperless
        - name: PAPERLESS_DBUSER
          value: paperless
        - name: PAPERLESS_DBPASS
          valueFrom:
            secretKeyRef:
              key: db-password
              name: paperless-secret
        image: ghcr.io/paperless-ngx/paperless-ngx:2.20.14
        imagePullPolicy: Always
        name: paperless-ngx
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/src/paperless/media
          name: media-volume
        - mountPath: /usr/src/paperless/data
          name: data-volume
      securityContext: {}
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: paperless-media-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: paperless-data-pvc

