apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    secret-key: ENC[AES256_GCM,data:cf/h32tFbV1jWFfXihbHEee8tK+HJIbH9zpjn+aIn3YXn2VI/stDwWtoidc+d/7iJQSL1yA4f0h88Euy,iv:nBsgkd8WvQhRaaKU+bqi2gi4E25XM+jFg7m971gze3s=,tag:DL/x4oGD5P7VROyVQAYoqw==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:ohwF5NYQo3CdsUKfDQb3QT22Xf6dWmq0s6YiD/ZksPw=,iv:a2HHFH2Mi1md1L+MEB99DorN7v/MZHZ1Bu66pYBmxdA=,tag:Hh311IhiJ41dj+fF8EDkvQ==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:5i/c41GeN8Vnu4T4PXBh4/oGEPYbLpVjKWju6hprxRw=,iv:23wQQ2r7lCHgTEBaIkhPMLskMeKageWlr+zGn9jWCdQ=,tag:60fDz2zODcnIgNxeQ3s01g==,type:str]
    pg-password: ENC[AES256_GCM,data:p2gtzh3wUJoBU9hRsFo5S6LvZfNe5xOVQ/c7dw==,iv:qrPIQDcXBmeXH6EwHyz/XkhsIqsnhrxXXho3YaxRNDM=,tag:atLgxgtk/Mt86bsFAzGI/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbElCc092ZUtzU1ZOZzdW
            QkpUcCs0OXJ5cW9UMktyNDNDYVdIMTFyVzEwCnlYdTJQdkwrc1VhU1AxRXZjY016
            cVE3YS8yQThGd2FJZzB3SXZQZVBBM0EKLS0tIC9rN2diMkJ2ZmhFbXJhYzRLS2VK
            RmwyZTJ1dHlHQ004Q2VZSWE2Q1Bmb1EKkHJqViiUPzfBOamoVZzFBPbkC4qL3jLX
            NeVM3nWqaO0W2nkGIYfZJqxEkaL492z+JjckbLkTwg8zfkwVnXqA5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T02:47:00Z"
    mac: ENC[AES256_GCM,data:kp/U4GJDO7jHM9JNgSKFpj2z0/tEpLBRjyya16OTFUn4NfqceRU2QcKZiY5RHQxbvDlzW/AH9LNH04en1/mtFp1p7ZkrUuD80LcwkJySu02HZqXfx/Q9VSuvNtot1mjXDa9WuMvBfSkSLnrKR0wnbhIm+H/Sa8+saq3Vg3szwIg=,iv:LR4mGc8yBXl+e/He8SQ8T+RBkD3KwTHbOVDDRVLYnLQ=,tag:G1VmV0CKUcHnRoFPB4KgZg==,type:str]
    version: 3.13.0
