apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "monitoring"
  nfs:
    path: /volume1/kub/homelab/monitoring/alert-manager
    server: __NAS-HOST__
  mountOptions:
    - nolock
    - noatime
    - nfsvers=4.1