apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-wasabi-creds
    namespace: velero
data:
    cloud: ENC[AES256_GCM,data:9ZbM6Vb3iN/+/R6hD0ZIo34XqVni1ofa0VwIkPNgq7BQyMp4CvjOXSTHqD4MTKqcJyI2+T+mtf9FH9e+hJngOuCguOERRuhVfTh7LWDSBtpdtENpVPfimr16VG3Rt8I+SsVYUjVgLI/LUt7sC+hK8xqunBLN8HDOrNOuY1IKy7Q70D6s5gJM3GF3bZlEKmKqAYUGhhF5hH8=,iv:6dOzlIu5u/6Re7UDD8XhjyVCqSH8JpEmV7D/LljV6DI=,tag:nWSBHVnEL5nhyFQfVeNr3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWJZL2NnZzdIMjVkc1h3
            MHp0bU1vRVFpdmlLVUU3aUZ0RG8yL0dxY2tVCjdvWFpNTGtXa3ZvU29EVk1QVHVv
            NkhFbTJ4Nmd5c1kyOVFWYWVkNThWNncKLS0tIFF4M0tRL3I1eTVIMXhWNjJ6eFB2
            OWI1Q3BVSnZXZzdjK0FkTUhZakVjejAKOV/Pu2c4Zt5prQTgp/XwOV7kOz2Gwh+u
            z7QpsW28SUjkO6OoVsL481+xeeX9sNYNosuRxxphWHtPpJjWWUfx2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:12:03Z"
    mac: ENC[AES256_GCM,data:IASEGLiQ/Zy9TpGP/nT0zbgLLUGTg3ZiLEqkxWjYVaFD/IWh4kVJ7gB9dl1THgDMjIHP6TfyQ+H79W7q1e+1Vlr3txPIoHcPHsywslQNE0HmSrrwEqtuVo7sCU9K5NSjkOb2/7oHbhibX5AwqUDXxVCuWnhPjkOMQLRvMOe+SzE=,iv:9Ml27OYNgVAIdFJ5ag8Nchik88uH+MqKrnDU56zFufU=,tag:b3qeJApHcmVSzPUcjCpr0g==,type:str]
    version: 3.13.0
