apiVersion: v1
data:
    repository-password: ENC[AES256_GCM,data:wp1TbAfD1Im+BO7lIGj9pDhbLZJl4DuQbzth/CDavyBlbXiP3ckZNQ5RFqc=,iv:HCEAUB7P8EN7noM9hnlf/hQuHBmV05ke4T0hVhijBtk=,tag:bnA1KADkjLQAwBPL/OknEw==,type:str]
kind: Secret
metadata:
    name: velero-repo-credentials
    namespace: velero
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ1dHc2d3T1NQNXFmd0p1
            NXJDM2IwTXQ4Q2FIWHJ1Wi83UWtuZTdpM20wClI4U2NjRkI5WHQvYm1DNkJCMTdZ
            MUdmdHdmblNQZlZMVUtYT3VvZmxqYUkKLS0tIFp3eklCVHNzS0RqWnRQc3RoQVlC
            a29JZ29CYkQvWnlLMDIzWU9ONE4rWWMK6loHZC/qP88m1ymeG1pK9vC/rBtySPP9
            YxCN3b5iy+YtsVx7R40nPeSHnbwniqyFClDeVRj73otO+LPTv4z3nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T20:28:41Z"
    mac: ENC[AES256_GCM,data:Jscp82D3F3tsyJhMuF2KQScuty0GUJDqBELf0h4r5fbUlEPSre2Ctc/QFAqusJ8QwOgg/AtugqrkxLt5JYhQsikkr8aFFcL1nzue7NQnRy+IZp0SpUy/8JP3K06fwCAVPBWqNSt4J7Lgrvf/dHqqHjIzvqT8XWcl9JTFp2xv9ec=,iv:+o2BAdMD9mJ5ha+5ic3iiLkeOftuWPjDxCOfhl8ejKM=,tag:F/9/lIsYECd8LF+IQsmDjA==,type:str]
    version: 3.13.0
