apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: guacamole-db-credentials
    namespace: guacamole
data:
    postgres-password: ENC[AES256_GCM,data:n9709nNa2V0XOZHdAIc9GQ==,iv:cE4TqmhDmCKKI6qXtNcqzGCDCRYOj+e4I8ZdPGyD8ZY=,tag:BNRiD/T7sCmpZpgPA5M+1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMloxd1NJZkt3eThCT25X
            Q092bHBocGZtMEphZ0dXaHlWVkpJMTBUSm53CmhrbjFGNHFxUlhQYTF4QnRCZ3hG
            dlNGci9kUVRWMlhwWnBYTkwrQnJQZkkKLS0tIDFsZmE4REkvajV5aHFZT2ZqV0lH
            ZmdLbTJJSXdJd2kwaXZUSGw0TUNkSDQKX/b3azzFBtIwldjvrpCT1smqxImue27d
            BqC7t5Aw+pl/LTl0VxajwjFAs6vm3St8L79So6VfXggMpBtLFg7IDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:07Z"
    mac: ENC[AES256_GCM,data:uJGG6Z24sOrjFLea16ebztPHVypTBVmjzEbbF+9kvoGX1nQcgdCyVV5bTTiJheSPqGzQrXe+H4mzFP0LndWe4DSxxLbmRuWIL9h+ct9qVlI6taMSu0/448egewiothidwEQa7TLgWk8JGaDa+tR9FJn4Pt2tYSBzFMo5Z90193g=,iv:vQ7RYULPz1bQFOMy6/fsCkmFzv8BjgacHUx3RTE/PYM=,tag:ultJ2BRuQFFUriieq+SgkA==,type:str]
    version: 3.13.0
