apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
  labels:
    app: drawio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
        - name: drawio
          image: jgraph/drawio:30.2.7
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_DNS
              value: drawio.${BASE_DOMAIN}
            - name: ORGANISATION_UNIT
              value: homelab
            - name: ORGANISATION
              value: homelab
            - name: COUNTRY_CODE
              value: US
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
