apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: drawio
  namespace: drawio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`drawio.${BASE_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: crowdsec-bouncer
          namespace: kube-system
      services:
        - name: drawio
          port: 80
