apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgres-backup
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage
  volumeName: nextcloud-postgres-backup-pv
