apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: nextcloud-rclone-wasabi
    namespace: nextcloud
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vhifD3yOiyIXebJem6RkA8YuHcd231iIj6fm6A==,iv:MP8dZWXuoPbJGgfzR4xzPTaIMXPwoJ7Jg+XG9JDwMlQ=,tag:EbWc6jIW9EfjSZNSSo81tw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jlMcWhaBKAbRQUemrixL4ZCwPRzjqwjNK/KZaq3b9awxC3D6EdwJ4SB85rcSdGyXFlsHfh39Rik=,iv:F6rAghkWUx7zeO6Czy4tGCzWER9j2vduxNhpQKoDRJw=,tag:i56OcYVJIiALmGTK21uS5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOEEzdDlBNzh6L1NWa283
            U1JRcDMrMFEzbW00aHB0VW1tOUViOUdZdjNvCmh5aFFjZ1Y2SzBJSk4vTUpnbEpa
            c2RPZkkwRmVoR2Q3OE1ibVYzcTRmemcKLS0tIEtxSlBrZWhWWXRpdVFxNmdQZ2pk
            eCtqQ1U4QjZ3dVNqQm5ZNzZCVzBXRUkKk0F2Q7M5s0bbiE1ciyzECXWauAzCNlYm
            uSBNb5nT6b9TvLMNML9TGfbdafJ5ivfsCD0g27LqQVNSd1HxAHj6ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:48:53Z"
    mac: ENC[AES256_GCM,data:QvSB346X7TvnAjuMV3aupg0HRgRz3npLOasMWAX08YYOIhtVhLARwenRG5zpfjnBwJVIAgJX4C25JStkWemlX/TRvH2M8E3oJY2iAIKLO/IlvzPZbKu7+pXgy35sh2+S4whCiL1IBeaSc68oELM8YGx8wHoZRmf1E/cRXEiZ8vw=,iv:r33shgy5PDuOwG8eGIg4vKVUJbvbGZfEH2dmxkyt1S8=,tag:FJDsoPQeaZ7t2U+EVUILNA==,type:str]
    version: 3.13.0
