apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-rclone-wasabi
    namespace: nextcloud
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TppBfj8wMWxFGe8Jjg/67m+jzqU=,iv:TxUvFaFXcWPJwqO5sDH9zCtBZFF0/5iicx1ENiqdFl0=,tag:nnVJTInXmSFkreQN4Q/fkw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:t4bziobTGKz8KFVclU9I5nGE14TzqTZcSBjNlgR2uG+zVxoK5zfaLg==,iv:yYpxtkANz2/kG0XdDma4kyMwyyltDjFgkN7uWCUjYC0=,tag:9pgEz6KcjFgGmYXpi0S+cQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOU0zU1Z6dXVJZXQzUW5w
            dk11ck9RT0w1TUw3dTJlbEppaVZFWFYwREdrCktvZjg5bkJYZy8xLzBZZ1pETVl6
            bi9Xd2tLeEI2cUJtU05zVDE4SWpmVEkKLS0tIGF4RHk2b0ZSeVRNZWNaTVpxSEFD
            S2VjM05YajdRaytjbnVxRDVTYkNFR2sKHFggJAS4JBJDoNYOSLNk2g1Hyh34ymsL
            6uUjvxt6/7J5cianGlSn3KADAQ93YmS3zyjUgUKIEZ0joy7UolXT8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:36:29Z"
    mac: ENC[AES256_GCM,data:92QnjCmHHnr0RNpfur9v1NnyOkQaMvyR1+Ho9V6syDhz+slbmgYPpce4pHMpwyTRzlxEsXvPP5v52rf3Gia8lWpTpculWKuXQduXbcfT9iKRjqe2V9JhcPa/7mTsfPp6XK/RcT/E6I/D4nxH9drAf/AhfvJRuPA9+hIT5/ygDKU=,iv:aXcAOqLMQpRHfni3AjL9u9jX8kC0RvLf5D+/4S9y+nw=,tag:4ouDzfTapPt3gWgASqnNFQ==,type:str]
    version: 3.13.0
