apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:phB8Rwfsu4ld+FZTHibI5R3UL6RnfTae9JqNAA5wQXI=,iv:Y7DHd8YowzMLALD055aMs01oijO+A8XOf+ze4gxuvNs=,tag:y0SJUo39Xzic4iE1f3pQ1Q==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:+GhI5CA=,iv:vs5tQ72r9Ma8vZTjA7mNR5pEJiCpgYTlSgvVNymxKhM=,tag:wKbxiVUeOte7fYUMYHg01g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K70M5e9HBKxy9z7TZ7ZCrc/+/NtcX9zL/bQf77YcVZM=,iv:uQ7CoHYBUuK8j/VzvxymTGBxLAaTh4dbEookVPgsmFs=,tag:0lNMEIETlSfWrbGIlaaaZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeXpRbzNyY21sOUo4ZHQz
            TGdndGpxNW1sL1hyd0RsTXBBTFJsYTAxOWc0ClhRVkJTQ0tJU1M3a1pQVjFQTGFJ
            U21DUlBLR2JyWWx4dEs2V2lyZm93UFkKLS0tIDRVNGlJS3ZxWXlVc1QzOG0vakIy
            UHErVzc5T3FESW1RN3B4YjRVb2JRVEEKlCnIAba017mhg78ID0vcDKwgvbPfoHqV
            p7CR+ivAl3kGTnY5awpF37hsq53fEe51I14PB/q6Cm6W1r00sHKGUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:34:04Z"
    mac: ENC[AES256_GCM,data:1kGhewasaXqmBvit2tT/U+KoZTE1W+AOEt82yyw/D86VQzufolZPKCJDbRJfFCvZGObDPMB9jNJkgwrEhnbCIA0/6ijp3XxwzS4gihaLEhK3BuVKkYd4Bed2XW2fKOfc/VfcWHWBStKaUj7cLAE/yZrm3nKAUhIxoSnPHDkbAPU=,iv:V/U3Rd59CBFr3oQnoC4l2VcDFidYtBF+C+S1HnfX/84=,tag:ZKnd7kyCn24Sc9ICASVkrw==,type:str]
    version: 3.13.0
