apiVersion: v1
kind: Service
metadata:
  name: ext-sw
  namespace: kube-system
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ext-sw-1
  namespace: kube-system
  labels:
    kubernetes.io/service-name: ext-sw
    endpointslice.kubernetes.io/managed-by: bastion-static
addressType: IPv4
ports:
- name: http
  protocol: TCP
  port: 80
endpoints:
- addresses:
  - __LAN-IP__
  conditions:
    ready: true
    serving: true
    terminating: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sw-jt-lab-net
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`sw.__BASE-DOMAIN__`)
    kind: Rule
    services:
    - name: ext-sw
      port: 80
      scheme: http
