apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: velero-ui
  namespace: velero
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`velero-ui.__BASE-DOMAIN__`)
      kind: Rule
      services:
        - name: vui-ui-clusterip-svc
          port: 80
