apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vs
  namespace: vscode
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vs.__BASE-DOMAIN__`)
      kind: Rule
      services:
        - name: code-server
          port: 80
