apiVersion: v1
kind: Service
metadata:
  name: backup-host-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: backup-host-exporter
spec:
  ports:
  - name: metrics
    port: 9101
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: backup-host-exporter
  type: ClusterIP

