apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-db
  claimRef:
    namespace: homelab
    name: guacamole-db-pvc
  nfs:
    server: ${NAS_HOST}
    path: /volume1/kubdbs/homelab/guacamole
    readOnly: false
