apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-db-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-db
  volumeName: guacamole-db-pv
