apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-exporter
spec:
  ports:
    - name: metrics
      port: 9798
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: speedtest-exporter
  type: ClusterIP
