apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  nfs:
    server: __NAS-HOST__
    path: /volume1/kub/homelab/uptime-kuma
    readOnly: false
