apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: vscode
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
  volumeMode: Filesystem
  storageClassName: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
        runAsGroup: 0
        supplementalGroups: [1000]
      containers:
        - name: code-server
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add: ["CHOWN", "SETUID", "SETGID"]
          image: lscr.io/linuxserver/code-server:latest
          ports:
            - containerPort: 8443
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscode-secret
                  key: password
            - name: SUDO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscode-secret
                  key: password
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: code-server-storage
      volumes:
        - name: code-server-storage
          persistentVolumeClaim:
            claimName: code-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: vscode
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  namespace: vscode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  ingressClassName: traefik
  rules:
    - host: vs.__BASE-DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server
                port:
                  number: 80
