apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - env:
        - name: GUACD_HOSTNAME
          value: guacd
        - name: POSTGRESQL_HOSTNAME
          value: guacamole-db
        - name: POSTGRESQL_DATABASE
          value: guacamole
        - name: POSTGRESQL_USER
          value: guacadmin
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: guacamole-db-credentials
        image: guacamole/guacamole:1.6.0
        imagePullPolicy: Always
        name: guacamole
        ports:
        - containerPort: 8080
          protocol: TCP
      securityContext: {}

