apiVersion: v1
kind: Secret
metadata:
    name: paloarp-credentials
    namespace: netalert
type: Opaque
stringData:
    PALO_API_KEY: ENC[AES256_GCM,data:fT07zTTMD7kAQKgcn3ZAY+GCbc19Zt8bhfvjwc9rQCSJVIHHK0p75N8u2knfwEUmYb2UBQqQ/Vkk2Y9No7OlQjsoQUHY11gyo4Bk37M4Oaal4Lfo/8lxXkitaPhIKvvK5NQtc9hvFLYtCGqHmDPG+ny+UaV6+1M+EmoLeI84dVckmxVn,iv:3aWcMLhV4i+UKGBks6d+I/u4qHWAsGF8rNxQt6ymIsc=,tag:wn2z5vQFUwznNQp8lGkS/Q==,type:str]
    PALO_HOST: ENC[AES256_GCM,data:FKKdsVY/cJ/Y,iv:MK5x8wTPsAWG3fSoYjF0nLOPyH4EkuVA0CUig//jv1Y=,tag:dFODKtE2vTTAx3TmN3mIjg==,type:str]
    PALO_VERIFY_TLS: ENC[AES256_GCM,data:4ml3TZM=,iv:w1Bz0AZ9tG9YBj7HQqmvNGeGPR/YdIxhOu2i7awrvFw=,tag:mN+C/Sg/pGzT3VBG/P5nhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM3BCbDc1QTZMSVdpVW5v
            SUM1cmp5MUx3aUJ0UTIwRHQwSUtXQXYxeVdZCjd4NlNpK0lXeEl0NWV2dGUwOVph
            TUpBemZ0elZIenlGQjRYd3ZUcUZUTDQKLS0tIHhqQVNEejgwcytyd3ZnRXZXNnRh
            cURESzhOYmpJWGNPalJEcnBITUVxaEkKRXVfulpUr+1m0bDLpZSBuKLudy9daWwD
            u7TSkJ7OBh//Jvxy0XK4qev0fkpdfB2M8594a3jeRFN+g5Iqm5uiaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T15:21:14Z"
    mac: ENC[AES256_GCM,data:6rDAyyd7qP+ylNFuczPAkuzBvNsOVHTYOuIv4Fpzui75DD/aZ+wDMlemQCeiYyssHvTmbwqpELvbatW9XV2AZbAxASUVLjpozObhImghg/D6pSx4adOcE+v9vCYXn5v9U2fHy87J/xz/70kagegQIPiC6gFlhNWrND0HAoMoY7E=,iv:Nx+yIMiz4Hlu0oeTdyeruW6Em0X0uSg7MENKzIb1ZMA=,tag:xEb6tIVpRzeNKwZkdqWESg==,type:str]
    version: 3.13.0
