apiVersion: v1
kind: Secret
metadata:
    name: paloarp-credentials
    namespace: netalert
type: Opaque
stringData:
    PALO_API_KEY: ENC[AES256_GCM,data:OnXTmFCDgVBLtsahhDOfKueVb6GjKWgFmX768L/ihb8Njzoj2F7JPU7Wkp47EHpdSLTn/y00ophWi3kNJ9bHsBQ0jfem7KyJOy0nRqNxkJ8AhT7DHnPF2AxSrGGwTFipsdQr4gEAjb/XCX/U9pplUNdtPp5ijyiy4QP1iytgfpIB9Gro,iv:HAnpU/lroHF1M3rxqaBctTwSWUA0Tc02vEi4/hK8LFY=,tag:v4ierNtj55h8BuFF9D6GVQ==,type:str]
    PALO_HOST: ENC[AES256_GCM,data:FKKdsVY/cJ/Y,iv:MK5x8wTPsAWG3fSoYjF0nLOPyH4EkuVA0CUig//jv1Y=,tag:dFODKtE2vTTAx3TmN3mIjg==,type:str]
    PALO_VERIFY_TLS: ENC[AES256_GCM,data:4ml3TZM=,iv:w1Bz0AZ9tG9YBj7HQqmvNGeGPR/YdIxhOu2i7awrvFw=,tag:mN+C/Sg/pGzT3VBG/P5nhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM3BCbDc1QTZMSVdpVW5v
            SUM1cmp5MUx3aUJ0UTIwRHQwSUtXQXYxeVdZCjd4NlNpK0lXeEl0NWV2dGUwOVph
            TUpBemZ0elZIenlGQjRYd3ZUcUZUTDQKLS0tIHhqQVNEejgwcytyd3ZnRXZXNnRh
            cURESzhOYmpJWGNPalJEcnBITUVxaEkKRXVfulpUr+1m0bDLpZSBuKLudy9daWwD
            u7TSkJ7OBh//Jvxy0XK4qev0fkpdfB2M8594a3jeRFN+g5Iqm5uiaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:55:15Z"
    mac: ENC[AES256_GCM,data:PcjEHW8s6Kk3ptQZfSOKzLifAVhzZOPdp7cPDhfN54BiyUGJAQL3GCDCF5luUw4VM+jHpCHnTE0EWCikUd48hAtkvw7UxcWUapgLFs/zMvKghSMG76f5EwUgb02d4f7HDCmvxbV0INfnC4dRMNe+bJ8FrxiLSRLYZYcKZ5RGMg4=,iv:zpXPq0l24mrwlXOewGusCmK2eTTJ4rVn7CGijfmkCtU=,tag:3flMOlg25ApraN8n4blndQ==,type:str]
    version: 3.13.0
