apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
  namespace: rss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage
  volumeName: freshrss-pv
