apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: snmp-exporter
spec:
  ports:
  - name: http
    port: 9116
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: snmp-exporter
  type: ClusterIP

