apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:/kulmXfWm2Gr,iv:MgNno2bwIFZONBLW41r66EfxTvvw+3SKvzqp9XdlNLA=,tag:mq0a++x13t9O+bqWtV0Wpg==,type:str]
    admin-user: ENC[AES256_GCM,data:BnGO3Ude,iv:f1Ioo4cbZ0zwxoKoCChtcZ0w64yz6W2UsbgzDVTtsVQ=,tag:/GtijY/4C433aeK75bBdIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjenNIVXRxMHpobjZhcmZD
            N0N4VlpXOHE2L1RWRyt3MjlSbzczLy9KdlVRCmc2V21RLzV3SEpMTkV5RGIxbHFv
            anBYTTMySmFvMGRMU1NRMCt3MWxLdmcKLS0tIDIzd2RnMzIydER0WjAvUDU0Mzkv
            WTR2SjRQSXBEcHBkMmNaT0xqWHYrQVUKF8Ye6I+v+vpwaAoHH7ORmCH36kMNWCRH
            3+Jma9sG4J3El+IEbyRyaXRNaJ3lw3n/0JEw5gXd4U7pZDbzo3xfpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:28:48Z"
    mac: ENC[AES256_GCM,data:uaLv7gBTpLG1Z6cvAzY7tRQCsZY9KvWK0D6cwShudlVIfszp/Agy2K2QXbQT1rk1ljitP4ejbIdM7idQmtT57HnskkpUStQlwzpMEbopXxTXK1loCFjQbM99kBDB85CKsXtQ+DyR3fz5fAaGM7LsZdRPFs+cuTaaC0zyYVQpz3c=,iv:dLjHJSsmkniTog1ZNBN1p3xC7Yjfu+vpTqAX25cMYf8=,tag:/InmAre0sPrFEScoBeq7LQ==,type:str]
    version: 3.13.0
