apiVersion: v1
kind: Secret
metadata:
    name: pushover-creds
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:B9dNoWcNpjIHG03kk/lnCSyLmsKmCzg6npt4PVbU,iv:WTSPxTZxFCSs6u6bO1aYfgc3tl5lIjcN/eOx3JwbJgg=,tag:yDSenNhXy2r9HOQ8C42HxA==,type:str]
    user_key: ENC[AES256_GCM,data:D0r3MomtElH4Hho8KfVUoA92Y257KJJDN5lh9uBP,iv:tgpL9wzNfd/a1FVrUHRcub8c17tO1IptXTNttxs9n5E=,tag:LQhV12oJ7/DSr2syU1/ZZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ3JZSjBlYlh0aDAxRUxZ
            MWErQnpjUlNFKzJobDJqdU1iREtNUXFxaURRCmhvVVRNSk1ETnkwRWpjczRrTHdC
            MG5IbzRNS0NGRTdsN1NhK3c5UUtwT28KLS0tIDJZSjVwR0Q1YmVrRldSNHNreFp6
            T2U3cDY5MTlsTW42YlZiSFN1R2UvMEEK6IIZJ2Zsk393xOcoGTlinsVZNdgUrm2d
            GTh2TsEINNltUNHV/oWD0TrxmLMJqgUayLoy2+bxrSdJF8sP+2/4Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T16:50:10Z"
    mac: ENC[AES256_GCM,data:ZN/lXk1PsHcQ2YcEVZAmjoHNXjElOp9OcD5/WpioTv0rIcpOYsiNIOfOYV1DQ1wvU/ioi+dQhL/Ho9xejIg5+8yL46y/lvhpdR/rCvVPmrWwj/Dh332GomHsXsaut05T4MFM3Pmg2Kyoc02VFQdrBiwhhDP8b3G9gb79+K2ppMU=,iv:MW1UcF7oMsMMJfDqDCiFUIBEuxyYS+Hs0k5rSjPAfN4=,tag:GFnl8Qz/ijbKL0bpgRy+5A==,type:str]
    version: 3.13.0
