apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:z6Gpcpswk9Gf5QASgpngqZ2N0hs19kG53TbOCa1cnVjNRNZ5XvjxqyWS2JRzOphgQXTMqOtTC5fkgZNm5iM+ZsykM3p6siTBb4CzdkJMezm0TOgCplK/PARc2qgkmX86yctP9XPx5WSlhhb5ber1E4jK+SDF5S+yqA==,iv:hPCEt61zv/b6J8hg13bBvAziAPIxpRm41eyATu/0eTo=,tag:MJbcc2UpmMeLDy+Mqzj9GA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d0NYUHhEelZib2twQ0FQ
            ejBkZm1xdUdyQzRHbWJXNU9aWWpJeVFsYmdNCnR1a1pQcENIeVJ0Nkxyc2NuNm9Q
            VEtKK2xTenFHbzhHdHNROWtMbm5DNVEKLS0tIFBKOFVaY2QwTWhQaG1Xc3J1Skgz
            MVhQbHJMMXg3dWY3aVF1aDBxQ01YVVEKTU77k9lsjZF7+hL8mF8Yy5LyJcnTOeKB
            XfGRkqLQIJlzsQzT7tLRSuTD15mFT64PC24WoAuLwmmTjYT/JWO0oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T20:14:09Z"
    mac: ENC[AES256_GCM,data:ZD9bEW6sj8TatZ1+FuVYkPmUqppC5gRR/ZGdIl/GJAwWCW38tdaJdoJXxVxzuROfbndDFPqNovyn75UHd+1zp/uEc0lMcqVt8oj/rinHCWQHT1MOQekn52vE8Q5tFA/BYSfZtMEkIan3tDHxyKaMK3HLOLKQHJSAD1rcQMEQyEc=,iv:dEDnAs+ZtjzVjgBb5g0iB5dUIxgAD6ouzC3+1DUhE0I=,tag:YvKKcRiPffaY+UAZUQryeQ==,type:str]
    version: 3.13.0
