apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: snmp-exporter-credentials
    namespace: monitoring
data:
    paloalto-auth-pass: ENC[AES256_GCM,data:cP3SSq9pJsuEMJSa,iv:wBUw+KHfHgbvGui5XqbjNdzYDU6p9Rdw1OpCaQtrNmU=,tag:z9j4UfW4ZyidxfmnzMp5CA==,type:str]
    paloalto-priv-pass: ENC[AES256_GCM,data:1q1vXG9i98cB/lLk,iv:EqHa7SpPKSTusHwgNSmpZ+eHmflPAXutb2zoHw+gmCw=,tag:6LRIET0Ggim/Qc8iRbz91w==,type:str]
    paloalto-username: ENC[AES256_GCM,data:3Ya2TnvRDqU=,iv:BfXmsJWyN+8zv4CH8dGQV/NrC5LPrbs/KPMYbT6h1GE=,tag:D9lpkiC/HV8KLarhsoEgpQ==,type:str]
    synology-auth-pass: ENC[AES256_GCM,data:uyj2Rp+ty4rNighM,iv:v3pb4iAiHWdzlh/9cfveR88kBsvxBeo/FTRuhCN98B8=,tag:wA+dBmAikGrIZE/dXHSB6g==,type:str]
    synology-priv-pass: ENC[AES256_GCM,data:YSNOXQoJhNC+Gg0K,iv:haqdJodDHfmBPeMOWcQRotGxPxWhFxWwGjEaHoluYKE=,tag:6PoOZb6Cx2v+ni3iU8gVcw==,type:str]
    synology-username: ENC[AES256_GCM,data:vpOyRg6hNj4=,iv:cgGpqFxTudj2OupXGWHbKFlBqFEEbxhYcPpTsUqKUGc=,tag:Ascs+nfHq7aF29+SSxzC4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieEoyYVZ3cFhBNHV0Y3dj
            TG9IRVFJNEZNUnVzSGhIem1ZcE9Ka21LMERJCmhPTXZKc1BuUmNFZWNUTHRrSW9a
            dGg1SWtvZXJoTEIyOVNMcFZnMXBtZXcKLS0tIFBGUmtZUzFhZHlZVjBtUlFiNkpX
            VS9MSCtFMVIyQW94Y0ViWmRxeVJwdnMKVrScJAKYssgsadYQ3RhBwmfZMIL9uj9h
            SalR62GoFcVCf9+HjVGUhAlhMeOHpFCQ8Esxqez73e8MR7S85fsz7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:07Z"
    mac: ENC[AES256_GCM,data:nAwwYCdD5S+ClVsp3ATWDeiyEhQ9S/vVpQ+XocqSFsILyQlz3qOGKib5t7Rdh0vJoiSmBS67yNAi39oKSrPrzbK5IjgqNb6TqbveczW7XekfWmHfonwHszk9JsnHrXYCSpxvdN3tOWTp87dduMkoS6wkCn5a6qFWExomqLNjvy0=,iv:ShP8P3MbpddqEsnCTJhbltC/I7dVGjK0Re/LvkAzvXk=,tag:ptYWpQZAtXYedQVKenRP2A==,type:str]
    version: 3.13.0
