apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pihole-exporter-credentials
    namespace: monitoring
data:
    pihole1: ENC[AES256_GCM,data:PzcANhk3zBx8t0ZiyQt8hFYMvl+jWiMGufUXCffFgZZ9we1+0JzuHSYLWI7rF5VDiOcIah+Wjq8OjplK,iv:TNOgRSvNppuxh4SsWWXt3chh+YNjc7IHv5wQbDVa2g8=,tag:qsSPYj9wE3Vy5JgGE1071A==,type:str]
    pihole2: ENC[AES256_GCM,data:jajrnrWFFXWVDkudLxPSfYX/uWB+3JcEm5hMW2Wxxg3mv40DQFCDCYIssrPEMsq1IYle/cVEYhHTz8yW,iv:fsAtCUpmFsN2keHkzcCHkKdY+vD5Kdxa/LEqSEsg3MM=,tag:l5nPHeLlckBE/MkIscDEHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NnZZOWxoYTlxQkZDY0ti
            RzV1ajZlUzlwbEYwUnA3ZUdHQi9CRmF6YkEwCkN4VWUrb1FhMDB3WFNuMjAvR2pt
            MEFVTUZWbEpFVFVzUWprc3dMOElKbTgKLS0tIDE1akFldUtaK2R0dU0yZmQ0SWg4
            ZUlTNjlKRGF5RHRZdk8rc2hRTzV4WDQKJUZY0Vbe4L9brjruWdWT/SejnXllgFjn
            4Pf5TtgrhIo9AkJvkJYf2i7D/796PPe3MJOGW2qcx3/+kKjlceREyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:07Z"
    mac: ENC[AES256_GCM,data:phniUwonto+pnKY2u5QiFcb5t19UBvbx+YpPdFAVD0FFQBfDnFO5/nqFPRzSgJJP4J75BEKs4fwS8yBBAqDyT30VExngpq32BCPy7PcQglfKLE7G6FBPBsNyBsMGRSKFzzsCirrICUHpQIPfUTix2ZHmUMmRvwVTXdNrp6d9JNU=,iv:+gSuz9SQwN0eO0t6JzU5HfV6LYVLBkdmJSaZ3BFsU+8=,tag:+oI/0TPN5Zd/MvLGRQP7xg==,type:str]
    version: 3.13.0
