apiVersion: v1
kind: Secret
metadata:
    name: backup-host-exporter-credentials
    namespace: monitoring
type: Opaque
stringData:
    token-name: ENC[AES256_GCM,data:nT+ol7dsjQ==,iv:lxPHnVa0/ZPflAharDiy6uuWzDsyFiZFBB5/zxhqalM=,tag:5N/QCAXzB9dLY5eUgtZISA==,type:str]
    token-secret: ENC[AES256_GCM,data:ZD2+/i2mXoMKMiBmsJBJZeNvCKKXSHdZEqPTFAxBrI2pj72W,iv:YnTZI8FsDYd3875+281yDNhDhd9DizGNTjPcZhln3Oc=,tag:bAw0QoH4mwOQGRjTmRQnCQ==,type:str]
    username: ENC[AES256_GCM,data:egTqb1yGM3zk,iv:WR7Nyvdc8w4n7zJQ6STLZuRvf71kofUtZYcSRP1SXcA=,tag:FOsE/BYiUg69tNqCCuROug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSkZOam90R0ZocEdnV21o
            UkF2NTF0STIrcjFvUnIvZzJsOEJIcm50MEg0CjM4M0hSLzBkRk1pcWhXcFR3NTE0
            LzdVK1B1eVFYaXpDZE44d1g5NDhzVHcKLS0tIFRnNmpDM1NHMzVlQ0poQkZWUnd0
            aVpmeFFTUnBHTnpYYkRvSGFUWFpXUDgKifWmkTDd54OXTrA4j2fd42Di/TK3DqQt
            ym4mfjPuyl3UOYXDZYvCubS6gregLzPsWS0DlNLIgzuniRTuk3qaIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:53:00Z"
    mac: ENC[AES256_GCM,data:ZWtcHhSGoKSJxE7qIAFrvu6oZ1DxZp+uHuTh+MQvhMC2/Z0e8+osnIMlcEysnvivihZ8iPK84E37mCzRs1gLacE/WFf15hO5bz7j6VDYnj6bljQvuMHLC1MdijQ6QD8NtA9It9Svr+1LUz8MsIQfy9bGTUwELF/hkb2jcu0C3ac=,iv:GCTqrHIXpo4+Tr+kQU4C7MokZW5Wm2NHx3BTqTUT964=,tag:IbMmxZkFsCMwds00lMdw9g==,type:str]
    version: 3.13.0
