---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-apps
  namespace: velero
  labels:
    tier: daily
spec:
  schedule: "0 3 * * *"
  template:
    defaultVolumesToFsBackup: true
    excludedResources:
      - events.events.k8s.io
      - events
    includedNamespaces:
      - dashy
      - drawio
      - firefly
      - fitjat
      - hoarder
      - homarr
      - homelab
      - it-tools-namespace
      - jellyfin
      - libre
      - loki
      - monitoring
      - n8n
      - netalert
      - nextcloud
      - paperless
      - rss
      - uptime-kuma
      - vscode
    snapshotVolumes: false
    storageLocation: wasabi
    ttl: 168h
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-apps
  namespace: velero
  labels:
    tier: weekly
spec:
  schedule: "0 4 * * 0"
  template:
    defaultVolumesToFsBackup: true
    excludedResources:
      - events.events.k8s.io
      - events
    includedNamespaces:
      - dashy
      - drawio
      - firefly
      - fitjat
      - hoarder
      - homarr
      - homelab
      - it-tools-namespace
      - jellyfin
      - libre
      - loki
      - monitoring
      - n8n
      - netalert
      - nextcloud
      - paperless
      - rss
      - uptime-kuma
      - vscode
    snapshotVolumes: false
    storageLocation: wasabi
    ttl: 672h
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monthly-apps
  namespace: velero
  labels:
    tier: monthly
spec:
  schedule: "0 5 1 * *"
  template:
    defaultVolumesToFsBackup: true
    excludedResources:
      - events.events.k8s.io
      - events
    includedNamespaces:
      - dashy
      - drawio
      - firefly
      - fitjat
      - hoarder
      - homarr
      - homelab
      - it-tools-namespace
      - jellyfin
      - libre
      - loki
      - monitoring
      - n8n
      - netalert
      - nextcloud
      - paperless
      - rss
      - uptime-kuma
      - vscode
    snapshotVolumes: false
    storageLocation: wasabi
    ttl: 8760h
