apiVersion: v1
kind: Secret
metadata:
    name: fitjat-secrets
    namespace: fitjat
type: Opaque
stringData:
    CF_ACCESS_AUD: ENC[AES256_GCM,data:KdrZShf2f5+hzKlqgpp3nA2JvZ+WqnfWpsnjnnUEULXBbfNpJuSZ0PaAnvMo0O75f7UcWxLLmKAQ0nDH4wYcRw==,iv:+1mf8uxcu6LFnhavoHdVKbtb52LUwzVjwvcvNPhWTgs=,tag:ZQKrzzRyzjAzaXSAzP4INA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcm83N2R3S2pvZmRPNFlD
            dGVxZTd2b05hV0M2MGpHRjBHaVNLaGJsQVNBCk4vaGhrR01sSXJTeFpZY1dLOThi
            UnNZSXllTitFemdQcGREeGxzRjJMYkUKLS0tIHJEL2VhL28yUTV2RTRlMnorRW1i
            WVQ3VDMybjh2czNHZG9jVk43L1RQMkkKIdqEDvazpOzArzgsLl/EpctmmzovxNBo
            aXhpkOGbNFMSck9BlirRu1y5tiKXbWENU8dEkqQA0ZYjvzCtMl5S5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T18:47:52Z"
    mac: ENC[AES256_GCM,data:MOZumOuvmgcOl+kmAwuQ0nRw/0YIAU367iQ8tXyaVspHnFU98LaHdvZpcrGRgTrwABOk1LSjQCJXa4SvMr/UrwLwtlHWQtAyy6v7pypKTZyyY5YpBsv1zUZGlS2J2tMOGPM7cRzz2zIe5vdUuk5vXLGYy40hsf0hkMubOvxeCxU=,iv:0qNvnIWcNWJpAvHBDz4ANJl54ozayMLIW7lpujXSTNU=,tag:ytc6GPj4rplibBTM+81VNg==,type:str]
    version: 3.13.0
