apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflared-token
    namespace: fitjat
data:
    token: ENC[AES256_GCM,data:6s8eMVPqQO6Wr1i/N1Yrc1il/GP3pwUEwQo2bKJKWPc2hNpBQ6KCuDrtPrjiTnhoXI+k+DXIV9yJvuVG5EVeoTzElmfS24a35cbfUKBZkgJi3SlxIGFvZyFGvHoP3KIAWf6zKnve+pFIcBrWEnalHX3tHdmkZUDk7dgQdFcdeSlm7R8Fg/jl6968NP5sq67yS+zjjo9SeyHtsMNZkpHjXocjn7M56fQac5cnytyHB5VaJS18eWFfX3uF2u4kTPVEvNSDtJD/xAymKshHAcxndlDB4S2zG0/Kx3UCD8H5vIvuKlU8depZWaG+Ilps/FffcXxB/nnfbXkmOACMtH3ALQw/pSBeYT1wjLstbu8k1CZkXOdNbfhXavE812GAx2jYSO7tII9sd266lkxuPJZHsRWUhnXX7/3TYTT/BjagjIZslbcoQ8Ji2126+qE=,iv:6BprPRx6I4DRWBU75gh86e2P4fUfOj8xt3XgEcZq3Uc=,tag:yJQQjErF3BZ+XdM9pLJTRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTk5mWjF6aXREbCt5M0ZX
            Rzl4bjFJZm5FNEk4Z2Jjc1B3dnc4WlhET1RnCnJ3cEY4N3N1REZZVHJYL0hTNlFL
            VkMvcU10UWduZTdWZW5wbkQ3Slc3SncKLS0tIEpOT1J6dHN6TXo4ZWhBVUdUa0l4
            OG1ERllOeUR0M1JlK2FsVVRyNjk4TFEKJ59c6rP346uJYJtmRLFK8zlZ243/3+9j
            z/rVMyWBpsuSVJsudVRe1SPcEewSKcfo8i+CfiPUvCKTunQPiP311g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T17:08:06Z"
    mac: ENC[AES256_GCM,data:4F5ZV1qdqW0XS7GbhQp8aiuRNQxz1phyGvneAu9f87nZ0FPcSWkJTFwmq+Qcu2l1NbxiXz0CQiIE3f63yfXEJC/3hLGsJGtADfPX6ZJIh+Q9xJtve8GLJBYWB//gg8Sm0nsWJxtePY8cI5uK+DVUTXf5Bp6H82ImRnjbMb6YHN4=,iv:/Ni6QIwzyatMUYx38zrOrnc8GpDo6AW10/2tO4vDiTM=,tag:aWYJXibINWiPPhyhTCMcRw==,type:str]
    version: 3.13.0
