apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-pvc
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: storage
  volumeName: cryptpad-pv
