# Source: https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution
#
# Committed example for the cluster-vars ConfigMap consumed by
# flux-system/kustomization.yaml's postBuild.substituteFrom.
#
# 21-key cluster-side surface — 1:1 with .env.example at repo root.
#
# Real-values copy lives off-tree at:
#   /Volumes/code/secrets/homelab/cluster-vars.yaml
# Apply via:
#   kubectl apply -f /Volumes/code/secrets/homelab/cluster-vars.yaml
#
# Variable name validation (Flux postBuild): ^[_[:alpha:]][_[:alpha:][:digit:]]*$
# Numbers and dotted strings MUST be quoted (RESEARCH Pitfall 4).
#
# This file's key set MUST match .env.example at repo root (21 keys). Plan
# 03-05 audits the two with a sorted-key diff for drift.
apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:btBqnnp7GYH9dUNcRuw=,iv:zNJw1yN1QiTcNvjkt27WyPx0aKFiNH0GboSUgbrijsw=,tag:juj+6skrfCYBeY7XlpVCMQ==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:DkL/i8N+GT+ktA==,iv:kf8hHWSE4uqmzjIfC3L5LK48v5YxFlUKpo58+7Rr794=,tag:Hoj5yqtOhEQeF65KID4eMQ==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:GgHBUWiGgijAg6CwFI1BtZCtq1n3zA==,iv:K1M5Sau2DkXqgFi2DfcnYhT2+sppuZjLx792waJg5/M=,tag:hAXktuThWmCBJGH3E3S3cg==,type:str]
    #ENC[AES256_GCM,data:h+oEaBew6ahIzWg6,iv:OXIkbldNJIRExjtUVlqDEW2JMbFvQ6rDBFULn1AGKLU=,tag:pEZE2RWBjbIEjZBDw/BFhQ==,type:comment]
    S3_BUCKET: ENC[AES256_GCM,data:NgXNV0/N1TKdQA==,iv:C+rGy2FGScCuxvabFYAjPFpcREP5oJApzEpidyuc9zc=,tag:+ilJR7kyIg5EAfw72Lxmig==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:ZrI/N4d06zaDNJ3GXPiG1kh5NBwD5T0Uwrs=,iv:OiH2chxDQezR3NhcNvON2Dcg0GpLgvGOfuZxoLrOqYI=,tag:Vx/UeBh1K1tGPKM0lQhQgA==,type:str]
    S3_REGION: ENC[AES256_GCM,data:yL38fQqC9xmd,iv:oFTGWfihMLv20Vbwz+T+nW8Gw5nmN0/OVWNJJj0pcfw=,tag:LFICH7eWEyOmybogZaqPUw==,type:str]
    #ENC[AES256_GCM,data:y/iFPQ==,iv:HI2mOqUFct1DO9twp739vMaSRjo0feCE0b9YBvEsvew=,tag:nQ9ky6KPeNs0ZO6n5wjkCw==,type:comment]
    NAS_HOST: ENC[AES256_GCM,data:qd8Nfr1GYcWR/5k=,iv:e1dKX9aoV4jztfAp4P0RIc2CSakWw1Dzr3KsXZa+0Cs=,tag:opc/uWwHnYtKb0owBKWLLg==,type:str]
    NAS_IP: ENC[AES256_GCM,data:Oauw251HonPQmrY=,iv:FidCE5E8VICrXLfDJoKOjXnhqvHzuYvt+uba2RsQT/s=,tag:ZfEruyOHcuOqs7n0lV7dcw==,type:str]
    #ENC[AES256_GCM,data:WMnXr3kQa90BtVrjyeXLw5kjG68J7CZpEv0=,iv:vSuTVPAypZUvUmTQa1PU54I2G8DnWTvQWa6uZ+Ou+fg=,tag:4dv9dq78IjLBXSBJ9g4qzQ==,type:comment]
    K3S_VIP: ENC[AES256_GCM,data:APjwx4WWqoaHmA==,iv:qVRY/a+BZKyFZ4kMRolm43Tj/4x18qeD/SqtWZRhYB0=,tag:1Lx6vhtOMgxv/P+jcGCqtQ==,type:str]
    K3S_API_IP: ENC[AES256_GCM,data:0SILrtCGv+EATw==,iv:XVz8affJsOFk5WsnctkO/1RJ/fBvoZnm6yyqBhBbJ9I=,tag:5MWThfNVA1lQfYf+VNTk7w==,type:str]
    PIHOLE1_IP: ENC[AES256_GCM,data:RtGMdnXTiQj/nQ==,iv:dby0b+xRQcnBkTeR+FGFOAPTPwyO89nOxmHJJTbpwsc=,tag:VFFajFO6fQnv/7BcAYPt7A==,type:str]
    PIHOLE2_IP: ENC[AES256_GCM,data:VTcdt0Ox/8Kdmw==,iv:eVJAZsZp4S+jgY+fSyyR1Bc54j6/YuHAgH+Xvrj+f8g=,tag:jslakXATdWKcbpc2FxyIMw==,type:str]
    #ENC[AES256_GCM,data:1e6CvaY6OACA6OkAte36ircHb38=,iv:y/bnQmmzSue9MQtkj5bdkt2wkb5zOIMQrx+56j2eqPU=,tag:CeocHpna4kmETDRzfe+xrg==,type:comment]
    LAN_MGMT_CIDR: ENC[AES256_GCM,data:Bl5KsxoIiYw8dXto,iv:VzhDQ+yij1I2LRh+wF5t4zz0Q74XRGOQNEMx3gTZHzs=,tag:RiJ0tMXNV4gwMeC4/nVQnw==,type:str]
    LAN_HV_CIDR: ENC[AES256_GCM,data:fjlcBMYiL1iLbnGo,iv:1FCdTvuTBowQrQj4jJvKPEO5S7op1lopHaBlNEB1zf4=,tag:NzTtr1L0rfpH0GGxaZjPeg==,type:str]
    LAN_SVC_CIDR: ENC[AES256_GCM,data:NVdymMuH7/L1JLWP,iv:z1UzjM4UWOQoeAzOiEWm6MC3NE/jSOaYoW+kOnXJT1s=,tag:+0Gbm1eom52mswoHvlcA5Q==,type:str]
    #ENC[AES256_GCM,data:6lFJXe9eklZRJTfIvBM/J7UB62U=,iv:9DsU7clkQ+Jhez6ePT9qOPOOZ/yIOUKNhqf8WHFxr/4=,tag:+CJJMndckVc3dYxq+t0MFA==,type:comment]
    PVE_API_HOST: ENC[AES256_GCM,data:JG4zBGIjckahEQ==,iv:XzwQ7xY5VuxrK4fT5EiCU0IDxYuL8LW35S3QjlxWfL4=,tag:mWdUghfMMZPS10QLFvA8mQ==,type:str]
    PVE_API_USER: ENC[AES256_GCM,data:fU5m/vUIdByDEw==,iv:ebdjNbTAFknRYnyCOLmINkJjg4DNE0lp+EOOI8U03ms=,tag:wrWpTzOFH96TW3Xqt4vMPA==,type:str]
    PVE_NODE_1: ENC[AES256_GCM,data:6C0Bhw==,iv:EYAYekiCABu/lYf0OIkTgvOJiu4l2QOAZXFSNQTITAo=,tag:Jei7bSDnj40KoAs+5Rt0UQ==,type:str]
    PVE_NODE_2: ENC[AES256_GCM,data:vD+RPg==,iv:T9wDKGdEKiJg/gecNbaWmOqasMwo20kgYJoIbV9Cmrs=,tag:V5eLdyjMYmPCXHU5Y6nV6Q==,type:str]
    PVE_NODE_3: ENC[AES256_GCM,data:U3HtQA==,iv:l3BZov6ORn/C1qx7Vv2J6Kl7Ew+3UNJm/EsbyvFTt7g=,tag:EejLFNImn0MZssKUxVBZiw==,type:str]
    #ENC[AES256_GCM,data:/dZ4WqqbNq5BvQkWqunUcrrhFgdQlYZy28ST,iv:lVjQ51bj2WgH2rAiw126RTDHiuaHECR/MJDFp7G6jvY=,tag:AirgZR4j9L3gzEO7KmQBEA==,type:comment]
    VCS_OWNER: ENC[AES256_GCM,data:7EnGuuS49IWpL6k=,iv:xGykUmZkWnZb2sk5JVsPZtvWG6cuIgE8j1ez9D6pTP8=,tag:RSF+4Q6j3lysJ2KNawX77w==,type:str]
    VCS_REPO: ENC[AES256_GCM,data:xTl19TczBg==,iv:53EMZDLer/cvRCoqaWDNMQBC0zOlxBvzJO110U6qSbU=,tag:kKE1gsf5DhokhK2wcCXBlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaVFvd0VmQlQwaVExdVYw
            Slp3QzRUN3ZUT2dCdlBzL2tBUFM5bTFiTnp3CnQrRkJvb3pTR2xEOXBJRHVsYUh3
            OGFyanIwK2lqa1IrRE10NFVML3RLU3MKLS0tICsvTmVCWlhPOGh1eUFtcGlPdVNm
            OVVZRlpicG5hSW1iT2svd2QzcHA3MVkK7V9bvqYbItUVltnun99/F3ebnqXD1GLz
            5CzzNPXyUn6sQLwxGIzmdYsb281Hnp9sPiK9USVhj49VcRf33HVFjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1neq36mupvqrk7tzcymh8u73f9araq4mffa47azfll7erdvq7tsuqylqrwq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T14:27:20Z"
    mac: ENC[AES256_GCM,data:Rd+R8qAus9bImCKE4XCbaUU1CLsUZpiZSTsKiPqTPv3Ui6fkcOqB/sJkhG0FEa7JUOqDQCFMArZZ9c+t8ZFP49UwFsXFbduViAQaJ2QyrA188/hnRutKyM0aHYwuBMswkvpMM2qs3/5ZQxCOi2zPCcEJc+lfKzxrLnBv+Z6Cn3g=,iv:6sqNvvOKmZJ453LXtOEaL2fePmNFTRVJCnQqvMwFnHk=,tag:ODoeD02EnoJMuywmiTodHg==,type:str]
    version: 3.13.0
